network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [20.0.0.10/24]
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
      routes:
      - to: default
        via: 20.0.0.1
